### ISSUE TITLE
[공용][백엔드] Redis - JWT, 이메일 모듈 (임시저장, Refresh token)

### ISSUE THREAD

**Issue by B-HS** [TEAM-ACO/aco-back#6]

**Comment by B-HS** [comment]
메일인증
1단계
이메일인증 요청 > mailsender로 요청된 이메일로 메일전송 >
메일전송과 동시에 redis에 전송 키 : email값으로 값 + 유효기간 설정 후 저장 

2단계
키 인증 시 >> 서비스에서 redis 전송키와 이메일 확인 >> 레디스에 키가 살아있다면 + 전송키가 맞으면 boolean true값 반환 틀리면 false값
혹시 관심있으십니까 ..
혹시 하신다면 넉넉하게 담주 월요일까지 .. 하시면 될듯한데

@PorkbellyBigfan 일정은 다음 주 화요일까지 가져봅시다 !

**Comment by PorkbellyBigfan** [comment]
레퍼런스 찾아보면서 해보겠습니다 화이팅
