### ISSUE TITLE
reportMember보냈을 때 SQL에 값이 asdf로 나오는 현상

### ISSUE THREAD

**Issue by k1k2brz** [TEAM-ACO/aco-back#68]
reportServiceImpl도 문제 없어보이는데 뭘까요..

**Comment by B-HS** [comment]
요건 테스트해봐야겠네여 ..

**Comment by B-HS** [comment]
![image](https://user-images.githubusercontent.com/49316060/211255447-65f220e0-3b01-419e-bf2c-77d9a18cd860.png)
swagger에서는 문제없어보이니 .. 

아마 이전 로직으로 하면 그냥 값이 이미 있어서 asdf값이 그대로 남아있는듯해영 
pr merge하시고 땡기셔서 보시면 수정되어있을겁니다
